name: Fuzzing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # corpus 저장 위해 write 필요
      actions: read
      security-events: write   # CodeQL 관련 설정 시 필요할 수 있음

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++
          sanitizer: address
          upload-build: true
          storage-repo: https://github.com/gyutrange/webgl-clusterfuzz-corpi.git
          project-src-path: .                     # 중요: 현재 루트 기준
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          language: c++
          sanitizer: address
          fuzz-time: 600
          storage-repo: https://github.com/gyutrange/webgl-clusterfuzz-corpi.git
          project-src-path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}

