name: Fuzzing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # corpus 저장 위해 필요
      actions: read
      security-events: write   # (선택) Code Scanning 경고 위해

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++
          sanitizer: address
          upload-build: true
          storage-repo: https://x-access-token:${{ secrets.ACTIONS_SECRET_PAT }}@github.com/gyutrange/webgl-clusterfuzz-corpi.git
          project-src-path: .

      - name: Run Fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          language: c++
          sanitizer: address
          storage-repo: https://x-access-token:${{ secrets.ACTIONS_SECRET_PAT }}@github.com/gyutrange/webgl-clusterfuzz-corpi.git

