name: Fuzzing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: c++
          sanitizer: address
          storage-repo: https://github.com/gyutrange/webgl-clusterfuzz-corpi.git
          upload-build: true

      - name: Run Fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          fuzz-time: 600
          storage-repo: https://github.com/gyutrange/webgl-clusterfuzz-corpi.git
          sanitizer: address
          language: c++

